export const PASSWORD_RESET_TOKEN_EXPIRATION_MINUTES = 10;
export const AUTH_TOKEN_EXPIRATION_DAYS = 7;
export const MIN_PASSWORD_LENGTH = 4;
export const EMAIL_VERIFICATION_CODE_EXPIRATION_MINUTES = 10;
export const VERIFICATION_CODE_LENGTH = 6;